### PR TITLE
Add searchrawtransaction

### PR DESCRIPTION
**Pull request by Roasbeef**
This pull request adds `btcjson` support for the "searchrawtransaction" RPC command. This PR is related to conformal/btcdb#11, and is another PR towards the completion of conformal/btcd#190. 

The defaults for the new RPC command have been copied from the initial implementation in a fork of `bitcoind` (verbose=true, skip=0, count=100).

### CODE REVIEW

**Comment by davecgh** [comment]
We'll need to reconcile this with #34 since they aren't compatible.

**Comment by davecgh** [comment]
If you rebase this on top of the latest master the build error should go away.

**Comment by davecgh** [comment]
A few points in relation with reconciling with #34:

* All of the Unmashal -> Unmarshal comment fixes are no longer necessary since the code is all gone.
* The need for the code in CreateMessageWithId is no longer necessary since that function is gone and it's all done via reflection
* The struct definition will need to change to use pointers for the optional fields and add a `jsonrpcdefault` tag with the relevant values
* All of the marshal/unmarshal code for the new command is no longer necessary since it's all done via reflection
* The `NewSearchRawTransactionCmd` function will need to change to the new format
* The `ReadResultCmd` function is gone, so that code can be removed

Also, the help portion of #34 isn't done yet, but it will likely be different.

**Comment by davecgh** [comment]
Actually, we should probably just go ahead and get this one merged first, and add a TODO to #34 to make sure the command added there before that pr is merged.  That seems a bit easier than redoing this entire pr.

**Comment by Roasbeef** [comment]
Rebased on top of master and it now successfully builds on Travis :+1:

Agree with just adding this to the current `btcjson`, since `btcjson2` will initially be in its own `v2/*` folder until it's fully phased in.

**Pull request merged**
